spring.application.name=makemytrip
server.port=8080
spring.data.mongodb.uri=mongodb+srv://sahanakn1603_db_user:pncbeK0x4uERg1Iq@makemytrip-cluster.nd2chfy.mongodb.net/?appName=makemytrip-cluster
spring.data.mongodb.database=makemytrip
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
# ==========================================================
# WEB PUSH / VAPID CONFIGURATION
# ==========================================================

webpush.vapid.public-key=BFParJ9A72KtrgZxWyAYiBvbd0dGRpEMloqwoOcWdTa0lBqnAzgB83wU1QSby21xpmgnKSpHEb2TQO2SluqwaUA
webpush.vapid.private-key=lWuTRv1RfaBjBvIIVuTMQf6UcMg4UBfzcMNFANNl7as
webpush.vapid.subject=mailto:kanasukn1603@gmail.com
